### ISSUE TITLE
failed to execute command: Text file busy (os error 26)

### ISSUE THREAD

**Issue by ignatenkobrain** [alexcrichton/cc-rs#144]
```
---- gnu_opt_level_1 stdout ----
	CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O1" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-o" "/tmp/gcc-test.7DEErspFO0gY/foo.o" "-c" "foo.c"


failed to execute command: Text file busy (os error 26)


thread 'gnu_opt_level_1' panicked at 'explicit panic', src/lib.rs:1140
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- gnu_opt_level_s stdout ----
	CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-o" "/tmp/gcc-test.EHYx83W179K5/foo.o" "-c" "foo.c"


failed to execute command: Text file busy (os error 26)


thread 'gnu_opt_level_s' panicked at 'explicit panic', src/lib.rs:1140


failures:
    gnu_opt_level_1
    gnu_opt_level_s

test result: FAILED. 15 passed; 2 failed; 0 ignored; 0 measured
```

**Comment by ignatenkobrain** [comment]
hmm, looks like it's getting random all the time.. now it's gnu_set_stdlib and gnu_opt_level_1

**Comment by alexcrichton** [comment]
This is probably running into a race here: https://github.com/alexcrichton/gcc-rs/blob/master/tests/support/mod.rs#L53. RUST_TEST_THREADS=1 should fix it quickly for now at least.
