### ISSUE TITLE
cc can't build with CC="/usr/bin/ccache /usr/bin/clang"

### ISSUE THREAD

**Issue by dholbert** [alexcrichton/cc-rs#298]
Similar to #297.  Apparently, something in the mozilla-central build process sets CC="/usr/bin/ccache /usr/bin/clang" if you're building with "ac_add_options --with-ccache" and CC=clang. And this triggers build errors like this:
````
 0:07.57    Compiling libloading v0.5.0
 0:07.62 error: failed to run custom build command for `libloading v0.5.0`
 0:07.62 process didn't exit successfully: `/scratch/work/builds/mozilla-inbound/obj/toolkit/library/debug/build/libloading-3174efe20a262dee/build-script-build` (exit code: 101)
 0:07.62 --- stdout
 0:07.62 cargo:rustc-link-lib=dl
 0:07.62 TARGET = Some("x86_64-unknown-linux-gnu")
 0:07.62 OPT_LEVEL = Some("1")
 0:07.62 TARGET = Some("x86_64-unknown-linux-gnu")
 0:07.62 HOST = Some("x86_64-unknown-linux-gnu")
 0:07.62 TARGET = Some("x86_64-unknown-linux-gnu")
 0:07.63 TARGET = Some("x86_64-unknown-linux-gnu")
 0:07.63 HOST = Some("x86_64-unknown-linux-gnu")
 0:07.63 CC_x86_64-unknown-linux-gnu = None
 0:07.63 CC_x86_64_unknown_linux_gnu = None
 0:07.63 HOST_CC = None
 0:07.63 CC = Some(" /usr/bin/ccache /usr/bin/clang")
 0:07.63 TARGET = Some("x86_64-unknown-linux-gnu")
 0:07.63 HOST = Some("x86_64-unknown-linux-gnu")
 0:07.63 CFLAGS_x86_64-unknown-linux-gnu = None
 0:07.63 CFLAGS_x86_64_unknown_linux_gnu = None
 0:07.63 HOST_CFLAGS = None
 0:07.63 CFLAGS = None
 0:07.63 DEBUG = Some("true")
 0:07.63 running: " /usr/bin/ccache /usr/bin/clang" "-O1" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "--target=x86_64-unknown-linux-gnu" "-Wall" "-Wextra" "-o" "/scratch/work/builds/mozilla-inbound/obj/toolkit/library/debug/build/libloading-485c286172c9e8bd/out/src/os/unix/global_static.o" "-c" "src/os/unix/global_static.c"
 0:07.63 
 0:07.63 --- stderr
 0:07.63 thread 'main' panicked at '
 0:07.63 
 0:07.63 Internal error occurred: Failed to find tool. Is `clang` installed?
 0:07.63 
 0:07.63 ', third_party/rust/cc/src/lib.rs:1984:5
 0:07.63 stack backtrace:
 0:07.63    0:     0x5649c3a8f02b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hb18bafd8df1a59a5
 0:07.63                                at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
 0:07.63    1:     0x5649c3a9592e - std::sys_common::backtrace::print::he2db06f5f327c580
 0:07.63                                at /checkout/src/libstd/sys_common/backtrace.rs:68
 0:07.63                                at /checkout/src/libstd/sys_common/backtrace.rs:57
 0:07.63    2:     0x5649c3a872e0 - std::panicking::default_hook::{{closure}}::hef814c3eb720780d
 0:07.63                                at /checkout/src/libstd/panicking.rs:381
 0:07.63    3:     0x5649c3a86e1c - std::panicking::default_hook::hf0d3601b84335f7c
 0:07.63                                at /checkout/src/libstd/panicking.rs:397
 0:07.63    4:     0x5649c3a876cb - std::panicking::rust_panic_with_hook::hf9f34d7f0d667943
 0:07.63                                at /checkout/src/libstd/panicking.rs:577
 0:07.63    5:     0x5649c3a8751e - std::panicking::begin_panic::h215af23ff6354aaf
 0:07.63                                at /checkout/src/libstd/panicking.rs:538
 0:07.63    6:     0x5649c3a8748a - std::panicking::begin_panic_fmt::h752224a2c436be23
 0:07.63                                at /checkout/src/libstd/panicking.rs:522
 0:07.63    7:     0x5649c3a72048 - cc::fail::h867170849d987964
 0:07.63                                at third_party/rust/cc/src/lib.rs:1984
 0:07.63    8:     0x5649c3a6a5bd - cc::Build::compile::h473be22458aa5d22
 0:07.63                                at third_party/rust/cc/src/lib.rs:875
 0:07.63    9:     0x5649c3a620d9 - build_script_build::main::h7920b511dd924b32
 0:07.63                                at third_party/rust/libloading/build.rs:27
 0:07.63   10:     0x5649c3a62355 - std::rt::lang_start::{{closure}}::h9ca8055de38f8055
 0:07.63                                at /checkout/src/libstd/rt.rs:74
 0:07.63   11:     0x5649c3a873e7 - std::panicking::try::do_call::h7d33aea9be52481f
 0:07.63                                at /checkout/src/libstd/rt.rs:59
 0:07.63                                at /checkout/src/libstd/panicking.rs:480
 0:07.63   12:     0x5649c3aa78ae - __rust_maybe_catch_panic
 0:07.63                                at /checkout/src/libpanic_unwind/lib.rs:101
 0:07.63   13:     0x5649c3a8ed49 - std::rt::lang_start_internal::h16c0c37ef62d8e5a
 0:07.63                                at /checkout/src/libstd/panicking.rs:459
 0:07.63                                at /checkout/src/libstd/panic.rs:365
 0:07.63                                at /checkout/src/libstd/rt.rs:58
 0:07.63   14:     0x5649c3a62347 - std::rt::lang_start::h90b178e1ae3c85cc
 0:07.63                                at /checkout/src/libstd/rt.rs:74
 0:07.64   15:     0x7f95f1728b96 - __libc_start_main
 0:07.64   16:     0x5649c3a60499 - _start
 0:07.64   17:                0x0 - <unknown>
 0:07.64 
````

**Comment by dholbert** [comment]
Reduced STR:
 (1) ensure /tmp/my-project is empty, and be sure `/usr/bin/ccache` exists. (e.g. `sudo apt-get install ccache`)

 (2) Run the following commands:
````
mkdir /tmp/my-project
cd /tmp/my-project
cargo init
echo libloading = \"0.5\" | tee -a Cargo.toml
CC="/usr/bin/ccache clang" cargo build
````

ACTUAL RESULTS:
Error output ending with:
````
CC = Some("/usr/bin/ccache clang")
[...]
running: "/usr/bin/ccache clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "--target=x86_64-unknown-linux-gnu" "-Wall" "-Wextra" "-o" "/tmp/my-project/target/debug/build/libloading-823a806b14f98686/out/src/os/unix/global_static.o" "-c" "src/os/unix/global_static.c"
[...]
Internal error occurred: Failed to find tool. Is `ccache clang` installed?
````


I get a successful compile if I strip off the leading "/usr/bin/" from ccache in the CC="..." variable, for whatever reason. So e.g. these work fine:
`CC="ccache clang" cargo build`
`CC="ccache /usr/bin/clang" cargo build`
...but these fail:
`CC="/usr/bin/ccache clang" cargo build`
`CC="/usr/bin/ccache /usr/bin/clang" cargo build`

**Comment by alexcrichton** [comment]
Thanks for the report! Mind giving the fix a spin to make sure it works?

**Comment by dholbert** [comment]
Thanks for fixing!  My STR still fail, but I assume that's because I'm getting the previous version, before the fix landed, since there hasn't been another version-bump after the fix.

What's the quickest way for me to test the fix?  (disclaimer: I am a cargo & rust newbie.)

**Comment by dholbert** [comment]
(One option, I think -- if you're confident enough to do a version-bump, I *think* that'll mean I can just run the STR and I'll automagically get the fixed code & find out if it's working or not. :)  But if there's another easy way for me to test locally before you do the version bump, I'm happy to try that too.)

**Comment by alexcrichton** [comment]
Ah no worries! Probably the easiest way (before publication) is to add this to the workspace root (probably the `Cargo.toml` with a `[workspace]` inside it):

```toml
[patch.crates-io]
cc = { git = 'https://github.com/alexcrichton/cc-rs' }
```

**Comment by dholbert** [comment]
Thanks! I appended that to the same `Cargo.toml` file that my STR uses in https://github.com/alexcrichton/cc-rs/issues/298#issuecomment-372844526 , and with that, I can successfully run `CC="/usr/bin/ccache clang" cargo build`.

So this does indeed seem to be fixed.

**Comment by alexcrichton** [comment]
Ok thanks! I'll hold off until https://github.com/alexcrichton/cc-rs/issues/300 is fixed for a new release
