### ISSUE TITLE
Can't execute compiler when cargo build --target=arm-linux-androideabi

### ISSUE THREAD

**Issue by kmorrissey-mersive** [alexcrichton/cc-rs#308]
I'm trying to build an Android NDK executable on Windows with a *.c file included. I've tried this using both Git Bash shell and Windows 10 CMD. My `build_android.cmd` build script is:

```
path %HOMEPATH%\android-21-toolchain\bin;%PATH%
set RUST_BACKTRACE=1
cargo build --target=arm-linux-androideabi
```

I get the following output when I `call build_android.cmd`:

```
Microsoft Windows [Version 10.0.16299.309]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Karen_Morrissey>cd WifiDisplay

C:\Users\Karen_Morrissey\WifiDisplay>call build_android.cmd

C:\Users\Karen_Morrissey\WifiDisplay>path [...]
C:\Users\Karen_Morrissey\WifiDisplay>set RUST_BACKTRACE=1

C:\Users\Karen_Morrissey\WifiDisplay>cargo build --target=arm-linux-androideabi
   Compiling wifi-display v0.1.0 (file:///C:/Users/Karen_Morrissey/WifiDisplay)
error: failed to run custom build command for `wifi-display v0.1.0 (file:///C:/Users/Karen_Morrissey/WifiDisplay)`
process didn't exit successfully: `C:\Users\Karen_Morrissey\WifiDisplay\target\debug\build\wifi-display-6bffab2bd3870f53\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("arm-linux-androideabi")
OPT_LEVEL = Some("0")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-pc-windows-msvc")
TARGET = Some("arm-linux-androideabi")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-pc-windows-msvc")
CC_arm-linux-androideabi = None
CC_arm_linux_androideabi = None
TARGET_CC = None
CC = Some("arm-linux-androideabi-clang")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-pc-windows-msvc")
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "arm-linux-androideabi-clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "--target=arm-linux-androideabi" "-I" "external/hostap/src/common" "-I" "external/hostap/src/utils" "-Wall" "-Wextra" "-DCONFIG_CTRL_IFACE" "-DCONFIG_CTRL_IFACE_UNIX" "-o" "C:\\Users\\Karen_Morrissey\\WifiDisplay\\target\\arm-linux-androideabi\\debug\\build\\wifi-display-4dacd8b23d0d3579\\out\\external/hostap/src/common\\wpa_ctrl.o" "-c" "external/hostap/src/common/wpa_ctrl.c"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is `arm-linux-androideabi-clang` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)

', C:\Users\Karen_Morrissey\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.9\src\lib.rs:2070:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: cc::fail
             at C:\Users\Karen_Morrissey\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.9\src\lib.rs:2070
   7: cc::Build::compile
             at C:\Users\Karen_Morrissey\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.9\src\lib.rs:881
   8: build_script_build::main
             at .\build.rs:48
   9: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  10: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  11: main
  12: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  13: BaseThreadInitThunk
```
I have tried running the same compile directly from the command line, and it works.

I did a little debugging, but I didn't really understand the underlying process spawning code. If I understand right, it thought the program file name did not exist. (Sorry I'm not more specific. I'm having trouble using Visual Studio Code to find again the place in the code where I saw the error value indicating program not found.)

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not too familiar with bat/cmd files but are you sure that this line configures the `PATH` env var?

```
path %HOMEPATH%\android-21-toolchain\bin;%PATH%
```

I think historically I've done something like `set PATH=...`, but there may be two ways!

Also, you're sure that `arm-linux-androideabi-clang` is installed at `%HOMEPATH%\android-21-toolchain\bin`? You could try running `arm-linux-androideabi-clang --version` in the script as well perhaps to see if `PATH` is set up right

**Comment by ArtemGr** [comment]
@alexcrichton , there is no `arm-linux-androideabi-clang` in the fresh Android NDK and it can't be installed.

```
/tmp$ android-ndk-r19/build/tools/make_standalone_toolchain.py --api 26 --arch arm --install-dir ndk/arm
WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm --api 26 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi26-clang++ src.cpp
```

We're supposed to use the prepackaged compilers now, and they are named a bit differently.

On Ubuntu I was able to workaround this mismatch with a symlink:

    export PATH=/tmp/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
    ln -s /tmp/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi26-clang /tmp/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-clang

**Comment by alexcrichton** [comment]
Interesting! I think this issue is somewhat out of date so I'm going to close, but @ArtemGr want to open a dedicated issue for the new Android compilers?

**Comment by ArtemGr** [comment]
> want to open a dedicated issue for the new Android compilers?

Good idea, but I'm exploring the [cross](https://github.com/rust-embedded/cross) compilation for now and it uses an older version of the NDK, so I'm unlikely to provide enough details at the moment.

**Comment by zoumi** [comment]
I got the same error. `arm-linux-androideabi-clang` is installed.

```
zoumi@zoumi-PC MINGW64 /h/work/AndroidStudioProjects/acom/rs-lib
$ cargo build --target arm-linux-androideabi --verbose
       Fresh cc v1.0.36
       Fresh autocfg v0.1.2
       Fresh rustc-demangle v0.1.14
       Fresh cfg-if v0.1.7
       Fresh void v1.0.2
       Fresh ascii v0.9.1
       Fresh either v1.5.2
       Fresh cesu8 v1.1.0
       Fresh jni-sys v0.3.0
       Fresh winapi-i686-pc-windows-gnu v0.4.0
       Fresh unreachable v1.0.0
       Fresh log v0.4.6
   Compiling backtrace-sys v0.1.28
       Fresh winapi v0.3.7
       Fresh libc v0.2.54
       Fresh byteorder v1.3.1
       Fresh bitflags v1.0.5
       Fresh memchr v2.2.0
     Running `E:\rustdir\target\debug\build\backtrace-sys-416974289b48bc51\build-script-build`
       Fresh winapi-util v0.1.2
       Fresh combine v3.8.1
       Fresh nix v0.12.0
       Fresh same-file v1.0.4
       Fresh walkdir v2.2.7
       Fresh serialport v3.2.0
error: failed to run custom build command for `backtrace-sys v0.1.28`
process didn't exit successfully: `E:\rustdir\target\debug\build\backtrace-sys-416974289b48bc51\build-script-build` (exit code: 1)
--- stdout
cargo:rustc-cfg=rbt
TARGET = Some("arm-linux-androideabi")
OPT_LEVEL = Some("0")
HOST = Some("i686-pc-windows-gnu")
CC_arm-linux-androideabi = None
CC_arm_linux_androideabi = None
TARGET_CC = None
CC = None
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
running: "arm-linux-androideabi-clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=arm-linux-androideabi" "-I" "src/libbacktrace" "-I" "E:\\rustdir\\target\\arm-linux-androideabi\\debug\\build\\backtrace-sys-a38a7f01dc0ef979\\out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=32" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "E:\\rustdir\\target\\arm-linux-androideabi\\debug\\build\\backtrace-sys-a38a7f01dc0ef979\\out\\src/libbacktrace\\alloc.o" "-c" "src/libbacktrace/alloc.c"

--- stderr


error occurred: Failed to find tool. Is `arm-linux-androideabi-clang` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)




zoumi@zoumi-PC MINGW64 /h/work/AndroidStudioProjects/acom/rs-lib
$ arm-linux-androideabi-clang
clang80: error: no input files
```

**Comment by zoumi** [comment]
I have this in .cargo/config, why it still try to search arm-linux-androideabi-clang???
```
[target.arm-linux-androideabi]
linker = "H:\\work\\AndroidStudioProjects\\acom\\rs-lib\\android-23-arm-linux-androideabi-4.9\\bin\\arm-linux-androideabi-gcc.cmd"
```
