### ISSUE TITLE
how to get the compile error?

### ISSUE THREAD

**Issue by calidion** [alexcrichton/cc-rs#393]
```
   Compiling cryptonote-raw-crypto v0.1.2 (D:\vigcoin\raw-crypto)
error: failed to run custom build command for `cryptonote-raw-crypto v0.1.2 (D:\vigcoin\raw-crypto)`
process didn't exit successfully: `D:\vigcoin\raw-crypto\target\debug\build\cryptonote-raw-crypto-c11d6a8377203080\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

Internal error occurred: Command "D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/FoD:\\vigcoin\\raw-crypto\\target\\debug\\build\\cryptonote-raw-crypto-84328b6ba0e97fd2\\out\\ext\\chacha.o" "/c" "ext/chacha.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

', C:\Users\eric\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\cc-1.0.35\src\lib.rs:2398:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\panicking.rs:381
   8: std::panicking::begin_panic_fmt
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\panicking.rs:336
   9: cc::fail
             at C:\Users\eric\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\cc-1.0.35\src\lib.rs:2398
  10: cc::Build::compile
             at C:\Users\eric\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\cc-1.0.35\src\lib.rs:951
  11: build_script_build::main
             at .\src\build.rs:14
  12: std::rt::lang_start::{{closure}}<()>
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\src\libstd\rt.rs:64
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\rt.rs:49
  14: std::panicking::try::do_call<closure,i32>
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\panicking.rs:293
  15: panic_unwind::__rust_maybe_catch_panic
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libpanic_unwind\lib.rs:87
  16: std::panicking::try
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\panicking.rs:272
  17: std::panic::catch_unwind
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\panic.rs:388
  18: std::rt::lang_start_internal
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\/src\libstd\rt.rs:48
  19: std::rt::lang_start<()>
             at /rustc/3750348daff89741e3153e0e120aa70a45ff5b68\src\libstd\rt.rs:64
  20: main
  21: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  22: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  23: BaseThreadInitThunk
  24: RtlUserThreadStart
```

with no c compile error.

**Comment by alexcrichton** [comment]
The error should show up naturally in the output, so it looks like this is a case where an error didn't show up but the process still exited abnormally. That can happen with wrapper scripts or otherwise crashing compilers that don't get a chance to print before they exit erroneously.

**Comment by calidion** [comment]
can this be improved?
